Spork/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^Spork/', include('Spork.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
    url(r'^$', 'sporkapp.views.subscribe'),
    url(r'^home/$', 'sporkapp.views.home'),
    url(r'^subscribe/$', 'sporkapp.views.subscribe'),
    url(r'^donations/$', 'sporkapp.views.donations'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root' : '/home/manvsmachine/Spork/Spork/sporkapp/media/'}),
    url(r'^admin/$', include(admin.site.urls))
)

Spork/sporkapp/models.py
from django.db import models

# Create your models here.

class Provider(models.Model):
    account_name = models.CharField(max_length=20)
    name = models.CharField(max_length=40)
    address = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=10)
    email = models.CharField(max_length=60)
    def __unicode__(self):
        return self.name
    
class Receiver(models.Model):
    account_name = models.CharField(max_length=20)
    address = models.CharField(max_length=40)
    phone_number = models.CharField(max_length=10)
    email = models.CharField(max_length=60)
    ein = models.CharField(max_length=20)
    def __unicode__(self):
        return self.account_name

class Donation(models.Model):
    DONATION_STATUS_CHOICES = (
        (u'available', u'available'),
        (u'claimed', u'claimed'),
        (u'expired', u'expired')
    )

    title = models.CharField(max_length=20)
    description = models.CharField(max_length=250)
    num_servings = models.IntegerField()
    expiration_time = models.IntegerField()
    time_created = models.DateTimeField()
    status = models.CharField(max_length=20, choices=DONATION_STATUS_CHOICES)
    donated_by = models.ForeignKey(Provider)
    claimed_by = models.ForeignKey(Receiver)
    time_claimed = models.DateTimeField()
    def __unicode__(self):
        return self.description

Spork/sporkapp/forms.py
from django import forms

from sporkapp.models import Donation

class SubscribeForm(forms.Form):
    email_address = forms.EmailField(required=True)
    firstname = forms.CharField(max_length = 30, required=False)
    lastname = forms.CharField(max_length = 30, required=False)

class NewDonationForm(forms.ModelForm):
    class Meta:
        model = Donation

Spork/sporkapp/views.py
import json
import urllib

from django.template import Context, loader
from django.shortcuts import render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext

from sporkapp.models import Donation
from sporkapp.forms import NewDonationForm, SubscribeForm

# Create your views here.
def subscribe(request):
    MAILCHIMP_API_KEY = ''
    MAILCHIMP_API_ENDPOINT_URL = 'http://us4.api.mailchimp.com/1.3/?method=listSubscribe'
    MAILCHIMP_LIST_ID = ''
    if request.method == 'POST':
        form = SubscribeForm(request.POST)
        if form.is_valid():
            api_params = {
                'apikey': MAILCHIMP_API_KEY,
                'id' : MAILCHIMP_LIST_ID,
                'email_address' : form.cleaned_data['email_address']
            }
            result = urllib.urlopen(MAILCHIMP_API_ENDPOINT_URL, json.dumps(api_params))
            result_json = json.loads(result.readlines())
            if result_json == True:
                return render_to_response('subscribe_thanks.html', context_instance=RequestContext(request))
        else:
            return HttpResponseRedirect('/home/')
    else:
        subscribe_form = SubscribeForm()
        return render_to_response('subscribe.html', {'subscribe_form' : subscribe_form}, context_instance=RequestContext(request))

def home(request):
    donations = Donation.objects.all()
    subscribe_form = SubscribeForm()
    return render_to_response('home.html', {'donations' : donations, 'subscribe_form' : subscribe_form})

def donation(request, donation_id):
    donation = Donation.objects.get(pk=donation_id)
    return render_to_response('donation_details.html', {'donation' : donation})

def create_donation(request):
    if(request.method) == 'POST':
        form = NewDonationForm(request.POST)
        if form.is_valid():
            return render_to_response('donation_thanks.html')
    else:
        form = NewDonationForm()
        return render_to_response('donate.html', {'form' : form})

Spork/sporkapp/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}Spork - Welcome{% endblock %}</title>
        
        <meta name="description" content="Welcome">
        <meta name="author" content="Spork">
        <meta name="viewport" 	content="width=device-width,initial-scale=1">
        

        <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
        <link href='http://fonts.googleapis.com/css?family=Asul:400,700' rel='stylesheet' type='text/css'>
        <link href="http://cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" media="all" href="/media/css/main.css" />
        <link rel="stylesheet" type="text/css" media="all" href="/media/css/landing.css" />
    </head>
    <body>
        <div id="header" class="container">
            <div class="row"><!-- header -->
                <div class="span6" id="logo">
                    {% block logo %}
                    {% endblock %}
                </div><!-- end of "logo" -->
                <div class="span10" id="navbar">
                    {% block nav %}
                    {% endblock %}
                </div><!-- end of "navbar" -->
            </div><!-- end of header row -->
        </div><!-- end of "header" -->
        <div id="main" class="container">
            {% block main %}
            {% endblock %}
        </div><!-- end of "main" -->
        <div id="footer" class="container">
            {% block footer %}
            {% endblock %}
        </div><!-- end of "footer" -->
    </body>
</html>

Spork/sporkapp/templates/claim.html
<!doctype html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>FAQs</title>
	
	<meta name="description" content="Frequently Asked Questions">
	<meta name="author" content="Spork">
	<meta name="viewport" 	content="width=device-width,initial-scale=1">
	

	<link rel="stylesheet" type="text/css" media="all" 	href="../media/css/reset.css" />
	<link rel="stylesheet" type="text/css" media="all" href="../media/css/960.css" />
	<link rel="stylesheet" type="text/css" media="all" href="../media/css/main.css" />
</head>

<body>
<div class="container_12">
	<!--Header Div -->
	<!--Logo Div-->
	<div class="grid_12">
		<div class="grid_5" id="logo">
		<div id="logo1">Sp</div><div id="logo2">ork</div>
		<div id="tagline">Where a good meal goes a long way</div>
		</div>
		<!--End Logo Div-->
	
	<!-- Navbar Div -->
	
		<div class="grid_6" id="navbar">
			<img src="../media/images/icons/facebook.png">
			<img src="../media/images/icons/twitter.png">
			<img src="../media/images/icons/tumblr.png">
			<img src="../media/images/icons/youtube.png">
			<img src="../media/images/icons/flickr.png">
			<br>
			<ul>
				<li><a href="/home">Home</a></li>
				<li><a href="/donate">Donate</li>
					<li><a href="/FAQ">FAQ</a></li>
					<li><a href="/contact">Contact</a></li>
				</ul>
			</div>
	</div>
	<div class="clear">&nbsp;</div>
	<!-- End Navbar Div-->
	<!--End Header Div-->
	
	<!--Top Section-->
	<div class="grid_12 topSection">
		<img src="../media/images/header.jpg">
	</div>
	
	<div class="clear">&nbsp;</div>
	<!--End TopSection-->
	
	<!--Spacer-->
	<div class="grid_12 spacer">
	</div>
	<div class="clear">&nbsp;</div>
	<!--End Spacer-->
	
	<!-- Content Area-->
	<div class="grid_7" id="content">
		<h2><a href="#">Sample Article Title</a></h2>
		<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet.</p>
	</div>
	
	<div class="grid_5" top_Section>
	
	</div>
	<div class="clear">&nbsp;</div>
	<!--End Content Area-->
	
	<!--Spacer-->
	<div class="grid_12 spacer">
	</div>
	<div class="clear">&nbsp;</div>
	<!--End Spacer-->
	
<!--Footer-->
<div class="grid_12" id="footer">
	<ul>
		<li>Copyright &copy; 2011 Spork</li>
		<li>Home</li>
		<li>Donate</li>
		<li>FAQ</li>
		<li>Contact</li>
	</ul>
</div>
<!--End Footer-->
</body>
</html>

Spork/sporkapp/templates/create_donation.html
<form action='/create_donation' method='post'>
    {{ form.as_p }}
    <input type='submit' value='submit' />
</form>

Spork/sporkapp/templates/donate.html
<!doctype html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Donate Today.</title>
	
	<meta name="description" content="Donate">
	<meta name="author" content="Spork">
	<meta name="viewport" 	content="width=device-width,initial-scale=1">
	

	<link rel="stylesheet" type="text/css" media="all" 	href="/media/css/reset.css" />
	<link rel="stylesheet" type="text/css" media="all" href="/media/css/960.css" />
	<link rel="stylesheet" type="text/css" media="all" href="/media/css/main.css" />
</head>

<body>
<div class="container_12">
	<!--Header Div -->
	<!--Logo Div-->
	<div class="grid_12">
		<div class="grid_5" id="logo">
		<div id="logo1">Sp</div><div id="logo2">ork</div>
		<div id="tagline">Where a good meal goes a long way</div>
		</div>
		<!--End Logo Div-->
	
	<!-- Navbar Div -->
	
		<div class="grid_6" id="navbar">
			<img src="../media/images/icons/facebook.png">
			<img src="../media/images/icons/twitter.png">
			<img src="../media/images/icons/tumblr.png">
			<img src="../media/images/icons/youtube.png">
			<img src="../media/images/icons/flickr.png">
			<br>
			<ul>
				<li><a href="/home">Home</a></li>
				<li><a href="/donate">Donate</li>
				<li><a href="/FAQ">FAQ</a></li>
				<li><a href="/contact">Contact</a></li>
				</ul>
			</div>
	</div>
	<div class="clear">&nbsp;</div>
	<!-- End Navbar Div-->
	<!--End Header Div-->
	
	<!--Top Section-->
	<div class="grid_12 topSection">
		<img src="../media/images/header.jpg">
	</div>
	
	<div class="clear">&nbsp;</div>
	<!--End TopSection-->
	
	<!--Spacer-->
	<div class="grid_12 spacer">
	</div>
	<div class="clear">&nbsp;</div>
	<!--End Spacer-->
	
	<!-- Content Area-->
	<div class="grid_8" id="content">
		<h1>Why waste food when </h1>
			
			<form action='/create_donation' method='post'>
			    {{ form.as_p }}
			    <input type='submit' value='submit' />
			</form>
			
	</div>
	
	<div class="grid_4" top_Section>
		<script src="http://widgets.twimg.com/j/2/widget.js"></script>
		<script>
		new TWTR.Widget({
		  version: 2,
		  type: 'profile',
		  rpp: 4,
		  interval: 30000,
		  width: 300,
		  height: 340,
		  theme: {
		    shell: {
		      background: '#0b7e88',
		      color: '#ffffff'
		    },
		    tweets: {
		      background: '#ffffff',
		      color: '#000000',
		      links: '#ff6600'
		    }
		  },
		  features: {
		    scrollbar: false,
		    loop: false,
		    live: false,
		    behavior: 'all'
		  }
		}).render().setUser('rhokatl').start();
		</script>
	</div>
	<div class="clear">&nbsp;</div>
	<!--End Content Area-->
	
	<!--Spacer-->
	<div class="grid_12 spacer">
	</div>
	<div class="clear">&nbsp;</div>
	<!--End Spacer-->
	
<!--Footer-->
<div class="grid_12" id="footer">
	<ul>
		<li>Copyright &copy; 2011 Spork</li>
		<li><a href="/home">Home</a></li>
		<li><a href="/donate">Donate</li>
		<li><a href="/FAQ">FAQ</a></li>
		<li><a href="/contact">Contact</a></li>
	</ul>
</div>
<!--End Footer-->
</body>
</html>

Spork/sporkapp/templates/home.html
<!doctype html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>FAQs</title>
        
        <meta name="description" content="Home">
        <meta name="author" content="Spork">
        <meta name="viewport" 	content="width=device-width,initial-scale=1">
        

        <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
        <link href="http://cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" media="all" href="/media/css/main.css" />
    </head>

    <body>
        <div class="container">
            <div class="row"><!-- header -->
                <div class="span6" id="logo">
                    <div id="logo1">Sp</div><div id="logo2">ork</div>
                        <div id="tagline">Where a good meal goes a long way</div>
                </div><!-- end of "logo" -- >
            
                <div class="span6" id="navbar">
                    <img src="../media/images/icons/facebook.png">
                    <a href="http://twitter.com/SporkATL"><img src="../media/images/icons/twitter.png"></a>
                    <img src="../media/images/icons/tumblr.png">
                    <img src="../media/images/icons/youtube.png">
                    <img src="../media/images/icons/flickr.png">
                    <br />
                    <ul>
                        <li><a href="/donate">Donate</a></li>
                        <li><a href="/FAQ">FAQ</a></li>
                        <li><a href="/contact">Contact</a></li>
                        <li><a href="/login">Login</a></li>
                    </ul>
                </div><!-- end of "navbar" -->
            </div><!-- end of header row -->
        
            <div class="row"><!-- top section -->
                <div class="span16 topSection">
                    <img src="../media/images/header.jpg">
                </div>
            </div><!-- end of top section row -->
            
            <div class="row"><!-- content -->
                <div class="span-two-thirds" id="content">
                    <form action="/subscribe" method="post">
                        <div class="clearfix">
                            <label for="id_email">* Email:</label>
                            <div class="input">
                                {{ subscribe_form.email }}
                            </div>
                        </div>
                        <div class="clearfix">
                            <label for="id_firstname">First Name:</label>
                            <div class="input">
                                {{ subscribe_form.firstname}}
                            </div>
                        </div>
                        <div class="clearfix">
                            <label for="id_lastname">Last Name:</label>
                            <div class="input">
                                {{ subscribe_form.lastname}}
                            </div>
                        </div>
                        <div class="clearfix">
                            <div class="input">
                                <input type="submit" class="btn info" value="Subscribe" />
                            </div>
                        </div>
                    </form>
                </div> 

                <div class="span-one-third"><!-- tweet widget -->
                    <script src="http://widgets.twimg.com/j/2/widget.js"></script>
                    <script>
                    new TWTR.Widget({
                      version: 2,
                      type: 'profile',
                      rpp: 4,
                      interval: 30000,
                      width: 320,
                      height: 340,
                      theme: {
                        shell: {
                          background: '#0b7e88',
                          color: '#ffffff'
                        },
                        tweets: {
                          background: '#ffffff',
                          color: '#000000',
                          links: '#ff6600'
                        }
                      },
                      features: {
                        scrollbar: false,
                        loop: false,
                        live: false,
                        behavior: 'all'
                      }
                    }).render().setUser('rhokatl').start();
                    </script>
                </div><!-- end of tweet widget -->
            </div><!-- end of content row -->
        
            <div class="row"></div><!-- spacer -->

            <div class="grid_12" id="footer">
                <ul>
                    <li>Copyright &copy; 2011 Spork</li>
                    <li><a href="/home">Home</a></li>
                    <li><a href="/donate">Donate</a></li>
                    <li><a href="/FAQ">FAQ</a></li>
                    <li><a href="/contact">Contact</a></li>
                </ul>
            </div><!-- end of "footer" -->
        </div><!-- end of "container" -->
    </body>
</html>

Spork/sporkapp/templates/landing.html
<!doctype html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>FAQs</title>
        
        <meta name="description" content="Home">
        <meta name="author" content="Spork">
        <meta name="viewport" 	content="width=device-width,initial-scale=1">
        

        <link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
        <link href="http://cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" media="all" href="/media/css/main.css" />
    </head>

    <body>
        <div class="container">
            <div class="row"><!-- header -->
                <div class="span6" id="logo">
                    <div id="logo1">Sp</div><div id="logo2">ork</div>
                        <div id="tagline">Where a good meal goes a long way</div>
                </div><!-- end of "logo" -->
            
                <div class="span6" id="navbar">
                    <img src="../media/images/icons/facebook.png">
                    <a href="http://twitter.com/SporkATL"><img src="../media/images/icons/twitter.png"></a>
                    <img src="../media/images/icons/tumblr.png">
                    <img src="../media/images/icons/youtube.png">
                    <img src="../media/images/icons/flickr.png">
                    <br />
                    <ul>
                        <li><a href="/donate">Donate</a></li>
                        <li><a href="/FAQ">FAQ</a></li>
                        <li><a href="/contact">Contact</a></li>
                        <li><a href="/login">Login</a></li>
                    </ul>
                </div><!-- end of "navbar" -->
            </div><!-- end of header row -->
        
            <div class="row"><!-- top section -->
                <div class="span16 topSection">
                    <img src="../media/images/header.jpg">
                </div>
            </div><!-- end of top section row -->
            
            <div class="row"><!-- content -->
                <div class="span-two-thirds" id="content">
                    <form action="/subscribe" method="post">
                        <div class="clearfix">
                            <label for="id_email">* Email:</label>
                            <div class="input">
                                {{ subscribe_form.email }}
                            </div>
                        </div>
                        <div class="clearfix">
                            <label for="id_firstname">First Name:</label>
                            <div class="input">
                                {{ subscribe_form.firstname}}
                            </div>
                        </div>
                        <div class="clearfix">
                            <label for="id_lastname">Last Name:</label>
                            <div class="input">
                                {{ subscribe_form.lastname}}
                            </div>
                        </div>
                        <div class="clearfix">
                            <div class="input">
                                <input type="submit" class="btn info" value="Subscribe" />
                            </div>
                        </div>
                    </form>
                </div> 

                <div class="span-one-third"><!-- tweet widget -->
                    <script src="http://widgets.twimg.com/j/2/widget.js"></script>
                    <script>
                    new TWTR.Widget({
                      version: 2,
                      type: 'profile',
                      rpp: 4,
                      interval: 30000,
                      width: 320,
                      height: 340,
                      theme: {
                        shell: {
                          background: '#0b7e88',
                          color: '#ffffff'
                        },
                        tweets: {
                          background: '#ffffff',
                          color: '#000000',
                          links: '#ff6600'
                        }
                      },
                      features: {
                        scrollbar: false,
                        loop: false,
                        live: false,
                        behavior: 'all'
                      }
                    }).render().setUser('rhokatl').start();
                    </script>
                </div><!-- end of tweet widget -->
            </div><!-- end of content row -->
        
            <div class="row"></div><!-- spacer -->

            <div class="grid_12" id="footer">
                <ul>
                    <li>Copyright &copy; 2011 Spork</li>
                    <li><a href="/home">Home</a></li>
                    <li><a href="/donate">Donate</a></li>
                    <li><a href="/FAQ">FAQ</a></li>
                    <li><a href="/contact">Contact</a></li>
                </ul>
            </div><!-- end of "footer" -->
        </div><!-- end of "container" -->
    </body>
</html>

Spork/sporkapp/templates/subscribe.html
{% extends "base.html" %}

{% block logo %}
    <a href="/"><span id="logo1">Sp</span><span id="logo2">ork</span></a>
    <div id="tagline">A good meal goes a long way</div>
{% endblock %}

{% block nav %}
    <!--<img src="../media/images/icons/facebook.png">
    <a href="http://twitter.com/SporkATL"><img src="../media/images/icons/twitter.png"></a>
    <img src="../media/images/icons/tumblr.png">
    <img src="../media/images/icons/youtube.png">
    <img src="../media/images/icons/flickr.png">
    <br />-->
    <!--<ul>
        <li><a href="/donate">Login</a></li>
        <li><a href="/FAQ">FAQ</a></li>
        <li><a href="/contact">Contact</a></li>
        <li><a href="/login">Sign Up</a></li>
    </ul>--!>
{% endblock %}

{% block main %}
    <div class="row"><!-- top section -->
        <div class="span-two-thirds">
            <!-- <img src="../media/images/header.jpg"> -->
            <h1 id="subscribeHeadline">Join our mailing list!</h1>
            <p id="subscribeContent">The team at Spork is hard at work. Sign up and we'll keep you up to date with new developments.</p>
            <form id="subscribeForm" action="/subscribe/" method="post">{% csrf_token %}
                <div class="clearfix">
                    <label for="id_email">Email Address:</label>
                    <div class="input">
                        {{ subscribe_form.email_address }}
                        <input type="submit" class="btn info" value="Subscribe" />
                    </div>
                </div>
            </form>
            <p id="subscribeDisclaimer">We take your privacy very seriously. We will not sell or distribute your email address to third parties or send you emails not related to Spork. We hate spam too.</p>
        </div>
        <div class="span-one-third"><!-- tweet widget -->
            <script src="http://widgets.twimg.com/j/2/widget.js"></script>
            <script>
            new TWTR.Widget({
              version: 2,
              type: 'profile',
              rpp: 4,
              interval: 30000,
              width: 300,
              height: 340,
              theme: {
                shell: {
                  background: '#0b7e88',
                  color: '#ffffff'
                },
                tweets: {
                  background: '#ffffff',
                  color: '#000000',
                  links: '#ff6600'
                }
              },
              features: {
                scrollbar: false,
                loop: false,
                live: false,
                behavior: 'all'
              }
            }).render().setUser('rhokatl').start();
            </script>
        </div><!-- end of tweet widget -->
    </div><!-- end of content row -->
{% endblock %}

{% block footer %}
    <div class="row">
        <ul>
            <li>Copyright &copy; 2011 Spork</li>
            <!--<li><a href="/">Home</a></li>
            <li><a href="/donate">Donate</a></li>
            <li><a href="/FAQ">FAQ</a></li>
            <li><a href="/contact">Contact</a></li>--!>
        </ul>
    </div><!-- end of row -->
{% endblock %}

Spork/sporkapp/templates/subscribe_thanks.html
{% extends "subscribe.html" %}


{% block main %}
    <div class="row"><!-- top section -->
        <div class="span-two-thirds">
            <!-- <img src="../media/images/header.jpg"> -->
            <h1 id="subscribeHeadline">Join our mailing list!</h1>
            <p id="subscribeContent">Thanks for signing up! We'll keep in touch.</p>
        </div>
        <div class="span-one-third"><!-- tweet widget -->
            <script src="http://widgets.twimg.com/j/2/widget.js"></script>
            <script>
            new TWTR.Widget({
              version: 2,
              type: 'profile',
              rpp: 4,
              interval: 30000,
              width: 300,
              height: 340,
              theme: {
                shell: {
                  background: '#0b7e88',
                  color: '#ffffff'
                },
                tweets: {
                  background: '#ffffff',
                  color: '#000000',
                  links: '#ff6600'
                }
              },
              features: {
                scrollbar: false,
                loop: false,
                live: false,
                behavior: 'all'
              }
            }).render().setUser('rhokatl').start();
            </script>
        </div><!-- end of tweet widget -->
    </div><!-- end of content row -->
{% endblock %}